[workspace]
members = [
    "examples/jaka_dual",
    "franka-rust",
    "libaubo-rs",
    "libhans-rs",
    "libjaka-rs",
    "rerun_urdf",
    "roplat_exrobot",
    "roplat_rerun",
    "rsbullet/rsbullet",
    "rsbullet/rsbullet-core",
    "./robot_behavior",
]
exclude = []
resolver = "3"

[patch.crates-io]
robot_behavior = { path = "./robot_behavior" }
roplat_exrobot = { path = "./roplat_exrobot" }
rsbullet_sys = { path = "./rsbullet/rsbullet-sys" }
