[package]
name = "jaka_dual"
version = "0.1.0"
edition = "2024"

[dependencies]
robot_behavior = { version = "0.5.1" }
libjaka = { path = "../../libjaka-rs" }
rsbullet = { path = "../../rsbullet/rsbullet" }
nalgebra = "0.34"
anyhow = "1.0.100"
roplat_rerun = { path = "../../roplat_rerun" }
